spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/my_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # 타임리프 캐시 끄기 (운영 시에는 true로 바꿔야 함)
  thymeleaf:
    cache: false

  # 정적 리소스(CSS, JS) 캐시 끄기
  web:
    resources:
      chain:
        cache: false

    #local p6spy
    p6spy:
      enable-logging: true
      # 쿼리 로그 출력 형식 지정 (기본값 외에 사용자 정의 가능)
      logging: slf4j
      multiline: true # 쿼리를 한 줄로 보지 않고 예쁘게 여러 줄로 보여줌